/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.BillController;
import javax.swing.JOptionPane;
import model.AppointmentDetails;

/**
 *
 * @author Admin
 */
public class BillView extends javax.swing.JFrame {

    /**
     * Creates new form BillView
     */
    public BillView() {
        initComponents();
        btnPrintReceipt1.setEnabled(true);
  
        this.setSize(new java.awt.Dimension(1200, 850)); 
    }
    private AppointmentDetails currentAppointment; // add as a class field
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBillAppointmentNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnLoadAppointment = new javax.swing.JButton();
        lblBillPatientName = new javax.swing.JLabel();
        lblBillTreatment = new javax.swing.JLabel();
        txtConsultationFee = new javax.swing.JTextField();
        btnGenerateBill = new javax.swing.JButton();
        lblTotalAmount = new javax.swing.JLabel();
        lblTreatmentFee = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtReceipt = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnPrintReceipt1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBillAppointmentNumber.setFont(new java.awt.Font("Frank Ruhl Hofshi", 1, 14)); // NOI18N
        getContentPane().add(txtBillAppointmentNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 253, 36));

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jLabel1.setText("Enter Appointment Number");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 288, -1));

        btnLoadAppointment.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        btnLoadAppointment.setText("Load Appointment");
        btnLoadAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadAppointmentActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoadAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 231, -1));

        lblBillPatientName.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        getContentPane().add(lblBillPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 247, 33));

        lblBillTreatment.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        getContentPane().add(lblBillTreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 247, 33));
        getContentPane().add(txtConsultationFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 253, 40));

        btnGenerateBill.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        btnGenerateBill.setText("Calculate and save bill");
        btnGenerateBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateBillActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerateBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 231, -1));

        lblTotalAmount.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        getContentPane().add(lblTotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 243, -1, 33));
        getContentPane().add(lblTreatmentFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(2468, 87, 247, 33));

        txtReceipt.setColumns(20);
        txtReceipt.setRows(5);
        jScrollPane2.setViewportView(txtReceipt);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 615, 297));

        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jLabel3.setText("Enter consultation fee in LKR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 288, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sunrise Dental Clinic - Search Appointment");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, -1));

        btnPrintReceipt1.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        btnPrintReceipt1.setText("Print receipt");
        btnPrintReceipt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintReceipt1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrintReceipt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 217, -1));

        jButton1.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 680, -1, -1));

        jButton2.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 680, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadAppointmentActionPerformed
        // TODO add your handling code here:
        String appointmentNumberStr = txtBillAppointmentNumber.getText().trim();

    BillController controller = new BillController();

    currentAppointment = controller.getAppointmentForBilling(appointmentNumberStr);

    if (currentAppointment != null) {

        lblBillPatientName.setText("Patient: " + currentAppointment.getPatientName());
        lblBillTreatment.setText("Treatment: " + currentAppointment.getTreatmentType());

    } else {

        JOptionPane.showMessageDialog(this, "No appointment found with that number.");
        currentAppointment = null;
    }
    }//GEN-LAST:event_btnLoadAppointmentActionPerformed

    private void btnGenerateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateBillActionPerformed
  if (currentAppointment == null) {
        JOptionPane.showMessageDialog(this, "Please load an appointment first.");
        return;
    }

    String feeText = txtConsultationFee.getText().trim();

    double consultationFee;

    try {
        consultationFee = Double.parseDouble(feeText);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid consultation fee.");
        return;
    }

    BillController controller = new BillController();

    String result = controller.generateBill(
            currentAppointment.getAppointmentNumber(),
            currentAppointment.getTreatmentType(),
            consultationFee);

    if (result.startsWith("BILL_SAVED:")) {

        String[] parts = result.split(":");
        String billId = parts[1];
        String treatmentFee = parts[2];
        String totalAmount = parts[3];

        lblTreatmentFee.setText("Treatment Fee: " + treatmentFee);
        lblTotalAmount.setText("Total Amount: " + totalAmount);

        StringBuilder receipt = new StringBuilder();
        receipt.append("========================================\n");
        receipt.append("       SUNRISE DENTAL CLINIC - RECEIPT\n");
        receipt.append("========================================\n");
        receipt.append("Bill ID:            ").append(billId).append("\n");
        receipt.append("Appointment No:     ").append(currentAppointment.getAppointmentNumber()).append("\n");
        receipt.append("Patient Name:       ").append(currentAppointment.getPatientName()).append("\n");
        receipt.append("Dentist:            ").append(currentAppointment.getDentistName()).append("\n");
        receipt.append("Treatment:          ").append(currentAppointment.getTreatmentType()).append("\n");
        receipt.append("Date:               ").append(currentAppointment.getAppointmentDate()).append("\n");
        receipt.append("Time:               ").append(currentAppointment.getAppointmentTime()).append("\n");
        receipt.append("----------------------------------------\n");
        receipt.append("Consultation Fee:   ").append(consultationFee).append("\n");
        receipt.append("Treatment Fee:      ").append(treatmentFee).append("\n");
        receipt.append("----------------------------------------\n");
        receipt.append("TOTAL AMOUNT:       ").append(totalAmount).append("\n");
        receipt.append("========================================\n");

        txtReceipt.setText(receipt.toString());

        JOptionPane.showMessageDialog(this, "Bill generated and saved successfully!");

    } else {

        JOptionPane.showMessageDialog(this, result);
    }
    }//GEN-LAST:event_btnGenerateBillActionPerformed

    private void btnPrintReceipt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintReceipt1ActionPerformed
        // TODO add your handling code here:
         if (txtReceipt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "No bill to print. Please generate a bill first.");
        return;
    }

    try {
        boolean printed = txtReceipt.print();

        if (!printed) {
            JOptionPane.showMessageDialog(this, "Print cancelled.");
        }

    } catch (java.awt.print.PrinterException e) {
        JOptionPane.showMessageDialog(this, "Printing failed: " + e.getMessage());
    }
    }//GEN-LAST:event_btnPrintReceipt1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to exit the system?",
            "Confirm Exit",
            JOptionPane.YES_NO_OPTION);

    if (choice == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         new SearchAppointmentView().setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateBill;
    private javax.swing.JButton btnLoadAppointment;
    private javax.swing.JButton btnPrintReceipt1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBillPatientName;
    private javax.swing.JLabel lblBillTreatment;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JLabel lblTreatmentFee;
    private javax.swing.JTextField txtBillAppointmentNumber;
    private javax.swing.JTextField txtConsultationFee;
    private javax.swing.JTextArea txtReceipt;
    // End of variables declaration//GEN-END:variables
}
