/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.BillController;
import javax.swing.JOptionPane;
import model.AppointmentDetails;

/**
 *
 * @author Admin
 */
public class BillView extends javax.swing.JFrame {

    /**
     * Creates new form BillView
     */
    public BillView() {
        initComponents();
    }
    private AppointmentDetails currentAppointment; // add as a class field
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBillAppointmentNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnLoadAppointment = new javax.swing.JButton();
        lblBillPatientName = new javax.swing.JLabel();
        lblBillTreatment = new javax.swing.JLabel();
        txtConsultationFee = new javax.swing.JTextField();
        btnGenerateBill = new javax.swing.JButton();
        lblTotalAmount = new javax.swing.JLabel();
        lblTreatmentFee = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtReceipt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter Appointment Number");

        btnLoadAppointment.setText("Load Appointment");
        btnLoadAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadAppointmentActionPerformed(evt);
            }
        });

        btnGenerateBill.setText("Calculate and save bill");
        btnGenerateBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateBillActionPerformed(evt);
            }
        });

        txtReceipt.setColumns(20);
        txtReceipt.setRows(5);
        jScrollPane2.setViewportView(txtReceipt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBillAppointmentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnLoadAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBillPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBillTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConsultationFee, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGenerateBill, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(188, 188, 188)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTreatmentFee, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTreatmentFee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLoadAppointment)
                                .addGap(69, 69, 69))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtBillAppointmentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)))
                        .addComponent(lblBillPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblBillTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(txtConsultationFee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btnGenerateBill)
                                .addGap(32, 32, 32)
                                .addComponent(lblTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadAppointmentActionPerformed
        // TODO add your handling code here:
        String appointmentNumberStr = txtBillAppointmentNumber.getText().trim();

    BillController controller = new BillController();

    currentAppointment = controller.getAppointmentForBilling(appointmentNumberStr);

    if (currentAppointment != null) {

        lblBillPatientName.setText("Patient: " + currentAppointment.getPatientName());
        lblBillTreatment.setText("Treatment: " + currentAppointment.getTreatmentType());

    } else {

        JOptionPane.showMessageDialog(this, "No appointment found with that number.");
        currentAppointment = null;
    }
    }//GEN-LAST:event_btnLoadAppointmentActionPerformed

    private void btnGenerateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateBillActionPerformed
  if (currentAppointment == null) {
        JOptionPane.showMessageDialog(this, "Please load an appointment first.");
        return;
    }

    String feeText = txtConsultationFee.getText().trim();

    double consultationFee;

    try {
        consultationFee = Double.parseDouble(feeText);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid consultation fee.");
        return;
    }

    BillController controller = new BillController();

    String result = controller.generateBill(
            currentAppointment.getAppointmentNumber(),
            currentAppointment.getTreatmentType(),
            consultationFee);

    if (result.startsWith("BILL_SAVED:")) {

        String[] parts = result.split(":");
        String billId = parts[1];
        String treatmentFee = parts[2];
        String totalAmount = parts[3];

        lblTreatmentFee.setText("Treatment Fee: " + treatmentFee);
        lblTotalAmount.setText("Total Amount: " + totalAmount);

        StringBuilder receipt = new StringBuilder();
        receipt.append("========================================\n");
        receipt.append("       SUNRISE DENTAL CLINIC - RECEIPT\n");
        receipt.append("========================================\n");
        receipt.append("Bill ID:            ").append(billId).append("\n");
        receipt.append("Appointment No:     ").append(currentAppointment.getAppointmentNumber()).append("\n");
        receipt.append("Patient Name:       ").append(currentAppointment.getPatientName()).append("\n");
        receipt.append("Dentist:            ").append(currentAppointment.getDentistName()).append("\n");
        receipt.append("Treatment:          ").append(currentAppointment.getTreatmentType()).append("\n");
        receipt.append("Date:               ").append(currentAppointment.getAppointmentDate()).append("\n");
        receipt.append("Time:               ").append(currentAppointment.getAppointmentTime()).append("\n");
        receipt.append("----------------------------------------\n");
        receipt.append("Consultation Fee:   ").append(consultationFee).append("\n");
        receipt.append("Treatment Fee:      ").append(treatmentFee).append("\n");
        receipt.append("----------------------------------------\n");
        receipt.append("TOTAL AMOUNT:       ").append(totalAmount).append("\n");
        receipt.append("========================================\n");

        txtReceipt.setText(receipt.toString());

        JOptionPane.showMessageDialog(this, "Bill generated and saved successfully!");

    } else {

        JOptionPane.showMessageDialog(this, result);
    }
    }//GEN-LAST:event_btnGenerateBillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateBill;
    private javax.swing.JButton btnLoadAppointment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBillPatientName;
    private javax.swing.JLabel lblBillTreatment;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JLabel lblTreatmentFee;
    private javax.swing.JTextField txtBillAppointmentNumber;
    private javax.swing.JTextField txtConsultationFee;
    private javax.swing.JTextArea txtReceipt;
    // End of variables declaration//GEN-END:variables
}
